version: '3'
services:
    app:
        build:
            context: ./docker/PHP8.0
            dockerfile: Dockerfile
        image: workspace-8.0/app
        volumes:
            - './projects:/workspace'
        networks:
            - workspace
networks:
    workspace:
        driver: bridge
